### PR TITLE
P57 solutions

### PR DESCRIPTION
**Pull request by audtjddld**
P57 Solutions pull request.

You have created a solution for the P57. It's a little different from what I created. Please check once.

### CODE REVIEW

**Review by loustler — CHANGES_REQUESTED** [review]
Plz resolve conflict.

It cannot merge and test.

**Comment by loustler** [comment]
@audtjddld If you resolve conflict with master branch, LGTM.

**Comment by loustler** [comment]
The releated issue is #16

**Comment by audtjddld** [comment]
I've solved the conflict of the code I committed.

**Review by loustler — APPROVED** [review]

**Comment by loustler** [comment]
@audtjddld 
I'll merge it

**Pull request merged**
