### PR TITLE
The solution for some exercise in chapter3

### PR DESCRIPTION
**Pull request by loustler**

### CODE REVIEW

**Comment by loustler** [comment]
The related issue is #10

**Comment by loustler** [comment]
And #13

**Comment by loustler** [comment]
And #14

**Review by audtjddld — CHANGES_REQUESTED** [review]
I've checked

**Comment by loustler** [comment]
@audtjddld What should i've changed?

**Review by audtjddld — APPROVED** [review]
???

**Comment by audtjddld** [comment]
-_- it is my mistake that i clicked wrong button.

**Comment by loustler** [comment]
The reference to omitted,
that issue is #3

**Pull request merged**
