### PR TITLE
Add solution for exercise 3.24

### PR DESCRIPTION
**Pull request by loustler**
The solution for exercise 3.24 

`hasSubsequence`

use tuple and recursive

### CODE REVIEW

**Comment by loustler** [comment]
The related issue is #15

**Comment by loustler** [comment]
@audtjddld 
If this solution is good you think, then merge it plz.

**Comment by loustler** [comment]
@audtjddld 
Don't update branch on the PR

**Comment by audtjddld** [comment]
plz come into slack

**Comment by audtjddld** [comment]
confess your heart
missing you @loustler

**Comment by loustler** [comment]
@audtjddld review plz

**Comment by loustler** [comment]
I understand no further comment for this PR.

Merge it.

**Pull request merged**
